<a href="https://colab.research.google.com/github/wmiguel29/IA_Optativa/blob/main/IA_EIA_Introducci%C3%B3nPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a Python
Python, a diferencia de otros lenguajes, no necesita definir los tipos de datos de las variables que usamos, lo cual, aunque a veces parece fácil, puede tender a cometer muchos errores, por lo que es bueno tenerlo en cuenta siempre.
A continuación, más que una introducción, es un pequeño resumen de las intrucciones y formas de manejar datos en Python, suponiendo que conoce otros lenguajes de programación.

## Tipos de datos contenedores

### Listas (Arreglos)

In [ ]:
arr=[] # Inicialización de un arreglo vacío
arr2=[2,4,5,20,3] # Arreglo de 5 elementos
arr3=['hola',3,8.3] # Arreglo de elementos diversos

In [ ]:
arr3

['hola', 3, 8.3]

In [ ]:
arr3.append(4) # Adicionar un elemento a arr3
arr3

['hola', 3, 8.3, 4]

In [ ]:
arr4=arr3 # Apuntan a la misma dirección de memoria
print(arr4)
arr4.append('ya')
print(arr4)
arr3

['hola', 3, 8.3, 4, 'ya', 10]
['hola', 3, 8.3, 4, 'ya', 10, 'ya']


['hola', 3, 8.3, 4, 'ya', 10, 'ya']

In [ ]:
arr5=arr4.copy()
arr4.append(10)
print(arr4)
arr5

['hola', 3, 8.3, 4, 'ya', 10, 'ya', 10]


['hola', 3, 8.3, 4, 'ya', 10, 'ya']

Los arreglos pueden servir como estructuras Pila (Stack), ya que tienen un método pop para extraer el último elemento.

In [ ]:
arr4.pop()

10

In [ ]:
arr4

['hola', 3, 8.3, 4, 'ya', 10, 'ya']

In [ ]:
arr6=range(10)
for a in range(5):
  print(a)

0
1
2
3
4


#### Matrices

In [ ]:
arr7=[[1, 2, 3], [4, 5, 6]]
print(arr7)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
print(arr7[0])
print(arr7[1]) # fila 1, todas las columnas
print(arr7[1][-1]) # último elemento de la fila 1

[1, 2, 3]
[4, 5, 6]
6


In [ ]:
print(len(arr7))
print(len(arr7[1]))

2
3


### Numpy

Numpy es una biblioteca que permite un tipo de dato lista que tiene más funciones y facilidades que los arreglos clásicos.

In [ ]:
# Importar biblioteca numpy
import numpy as np

In [ ]:
narr=np.array([])# Crear un numpy vacío
narr=np.append(narr,3)
narr

array([3.])

In [ ]:
narr=np.append(narr,'ya')# Los elementos del numpy, por defecto son del mismo tipo, si hacemos esto cambiamos el primer tipo de dato
narr

array(['3.0', 'ya'], dtype='<U32')

In [ ]:
narr1=np.array(['ya',1, 2.3])
print(narr1.dtype)
narr1

<U3


array(['ya', '1', '2.3'], dtype='<U3')

In [ ]:
narrFloat = np.array([],dtype='float64') 
narrFloat = np.append(narrFloat,8.5)
print(narrFloat.dtype) 
narrFloat = np.append(narrFloat,'ya')
print(narrFloat.dtype)

float64
<U32


In [ ]:
narray5=np.array([[1, 2, 3], [4, 5, 6]])
narray5

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
narray5=np.append(narray5,np.array([[7],[8]]),axis=1) # adición por columnas
narray5

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [ ]:
narray5=np.append(narray5,[[9,10,11,12]],axis=0) # adición por filas
narray5

array([[ 1,  2,  3,  7],
       [ 4,  5,  6,  8],
       [ 9, 10, 11, 12]])

In [ ]:
print(narray5.shape)

(3, 4)


In [ ]:
print(narray5[:,2]) # columna 2, todas las filas
print(narray5[1,:]) # fila 1, todas las columnas
print(narray5[1,-1]) # último elemento de la fila 1
print(narray5[:2, 1:3]) # Primeras dos filas y columna de la 1 a la 3-1=2

[ 3  6 11]
[4 5 6 8]
8
[[2 3]
 [5 6]]


In [ ]:
npRandom=np.random.random((2,2))
npRandom

array([[0.55083009, 0.67038974],
       [0.5974226 , 0.99716291]])

In [ ]:
nzeros=np.zeros((2,2)) # Crear matriz inicializada en cero
print(nzeros)
nones=np.ones((2,3)) # Crear matriz inicializada en unos
print(nones)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
narray2=np.arange(10) # Crear arreglo con números del 0 al 9
narray2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
narray4=np.full(5,4) # Crear arreglo de tamaño 5 inicializada en 4
print(narray4)
narray3=np.full((2, 5), 8) # crear matriz de 2x5 inicializada en 8
narray3

[4 4 4 4 4]


array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [ ]:
a=np.empty(5, dtype=int)# crear arreglo 'vacío' de tamaño 5
a.fill(2) # rellenarlo con 2
print(a)

[2 2 2 2 2]


#### Métodos interesantes de Numpy

Para ver cuáles elementos cumplen con una condición en un numpy:
Por ejemplo los elementos que son pares en narray5

In [ ]:
print(narray5)

[[ 1  2  3  7]
 [ 4  5  6  8]
 [ 9 10 11 12]]


In [ ]:
#Condición booleana
cond= narray5%2==0
cond

array([[False,  True, False, False],
       [ True, False,  True,  True],
       [False,  True, False,  True]])

In [ ]:
narray5[cond]

array([ 2,  4,  6,  8, 10, 12])

Ver índices que cumplen con una condición, para eso está la función **where** o **argwhere**

In [ ]:
indexCond=np.where(narray5%2==0)
print(indexCond)
print(narray5[indexCond])
print(np.argwhere(narray5%2==0))
[narray5[r,c] for [r,c] in np.argwhere(narray5%2==0)] # Creación de un arreglo a partir de un resultado de un for each

(array([0, 1, 1, 1, 2, 2]), array([1, 0, 2, 3, 1, 3]))
[ 2  4  6  8 10 12]
[[0 1]
 [1 0]
 [1 2]
 [1 3]
 [2 1]
 [2 3]]


[2, 4, 6, 8, 10, 12]

**argmax**: devuelve el índice del mayor elemento, puede calcularse en el arreglo completo o si es una matriz puede especificarse el eje: fila o columna

In [ ]:
narray8=np.round(np.random.random((3,5))*100)
print(narray8)
print(np.argmax(narray8,axis=0)) # Índice del máximo elemento por columna
print(np.argmax(narray8,axis=1)) # Índice del máximo elemento por fila

np.argmax

[[67. 36. 67. 44. 22.]
 [15. 21. 34. 98. 93.]
 [12. 62. 72. 80.  3.]]
[0 2 2 1 1]
[0 3 3]


Si necesito saber más de uno, por ejemplo que el máximo se repita

In [ ]:
ejarray=np.array([3, 12, 2, 6,12,8])
print(np.argmax(ejarray)) # Devuelve el primero
indexAllMax=np.where(ejarray == np.amax(ejarray))
print(indexAllMax)

1
(array([1, 4]),)


### Tuplas

In [ ]:
t = (3, 6)  # Crear una tupla con valores 3 y 6
print(t[0])

3


Array de tuplas

In [ ]:
atuple=[('No',0),('Si',1)]
print(atuple[0])
print(atuple[0][1])

('No', 0)
0


### Set
Es un conjunto desordenado de elementos


Como conjuntos son usados generalmente cuando se necesita hacer chequeos de pertenencia, eliminación de duplicados de una secuencia y cálculo de operaciones matemáticas como intersección, unión, diferencia y diferencia simétrica.

In [ ]:
set1={'libro','cuaderno','mesa', 2}

In [ ]:
print('mesa' in set1)
print('gato' in set1)

True
False


**isdisjoint(set2)**: devuelve verdadero si no tiene elementos en común con set2

**intersection(set2)**: devuelve la intersección entre los conjuntos

**union(set2)**: devuelve la unión de los conjuntos sin repeticiones

**difference(set2)**: devuelve los elementos que están en el primer conjunto y no están en set2


In [ ]:
set2={'gato','mesa','libro','perro'}
print(set1.isdisjoint(set2))
set3={'gato','perro'}
print(set1.isdisjoint(set3))

print(set3.issubset(set2))
print('Intersección:',set1.intersection(set2))

print('Union:',set1.union(set2))

print('Diferencia:',set1.difference(set2))
print('Diferencia:',set2.difference(set1))

False
True
True
Intersección: {'mesa', 'libro'}
Union: {2, 'cuaderno', 'gato', 'libro', 'mesa', 'perro'}
Diferencia: {2, 'cuaderno'}
Diferencia: {'gato', 'perro'}


### Diccionarios

In [ ]:
dic={'Nombre':'Juan Pérez','Edad': 20, 'Notas':[4,5,4.3,3]}
print(dic['Nombre'])
print(dic['Notas'])
print(round(sum(dic['Notas'])/len(dic['Notas']),1))

Juan Pérez
[4, 5, 4.3, 3]
4.1


In [ ]:
dic2=dict(Nombre='Juan', Edad=20, Notas=[4,5,4.3,3])
dic2

{'Edad': 20, 'Nombre': 'Juan', 'Notas': [4, 5, 4.3, 3]}

## Ciclos

El **for each** de python es muy potente y muy rápido porque está programado en C.

Se puede usar de diferentes formas:
- recorrer un arreglo como se ha visto anteriormente, o cualquiera de los contenedores anteriores
- crear un arreglo a partir de un resultado secuencial en una ciclo

Para este último por ejemplo: Suponga que se quieren seleccionar los elementos mayores que 5 y dividirlos 10.

In [ ]:
## Creando arreglos con un ciclo
ejArray=[3,20,5,12,10,9,50]
ex1=[e/10 for e in ejArray]
print(ex1)
ex=[e/10 for e in ejArray if e>5] # El if va al final del for de forma que se va a ejecutar sólo para esa condición
ex

[0.3, 2.0, 0.5, 1.2, 1.0, 0.9, 5.0]


[2.0, 1.2, 1.0, 0.9, 5.0]

Suponga que se quiere: Hacer un nuevo arreglo donde los que son mayores que 5 los divida por 10 y los que son menores los multiplique por 2.

In [ ]:
[e/10 if e>5 else e*2 for e in ejArray] # En este caso el if va delante porque también se va a hacer una acción para el else

[6, 2.0, 10, 1.2, 1.0, 0.9, 5.0]

In [ ]:
[ejArray[e]/10 if ejArray[e]>5 else ejArray[e]*2 for e in range(0,5)]

[6, 2.0, 10, 1.2, 1.0]

El if también se puede usar así para asignar un valor

In [ ]:
a= 20
b= a/10 if a>5 else a*2
b

2.0

Cuando necesitamos recorrer un arreglo con índices o sea en un rango de 0 a N

In [ ]:
for i in range(len(ejArray)):
  print(i,':',ejArray[i])

0 : 3
1 : 20
2 : 5
3 : 12
4 : 10
5 : 9
6 : 50


O también podemos usar **enumerate** que devuelve una tupla donde tenemos el ínice y el arreglo en el índice

In [ ]:
for i,e in enumerate(ejArray):
  print(i,':',e)

0 : 3
1 : 20
2 : 5
3 : 12
4 : 10
5 : 9
6 : 50


while se usa con una condición (sólo que es mucho más lento que el for)

In [ ]:
i=0
while i<len(ejArray):
  print(i,':',ejArray[i])
  i+=1

0 : 3
1 : 20
2 : 5
3 : 12
4 : 10
5 : 9
6 : 50


Iterar un diccionario:

Como los diccionarios se manejan como tablas hash, uno puede acceder a su llave (key) o a sus elementos asociados a cada key

In [ ]:
for key in dic:
  print(key)

Nombre
Edad
Notas


In [ ]:
for key in dic:
  print(key,':',dic[key])

Nombre : Juan Pérez
Edad : 20
Notas : [4, 5, 4.3, 3]


También se puede acceder a la key y el valor a la vez con la función items()

In [ ]:
dic.items()

dict_items([('Nombre', 'Juan Pérez'), ('Edad', 20), ('Notas', [4, 5, 4.3, 3])])

In [ ]:
for k,v in dic.items():
  print(k,':',v)

Nombre : Juan Pérez
Edad : 20
Notas : [4, 5, 4.3, 3]


## Clases

Las clases en python tienen un método __init__ que es el constructor.

Los atributos se definen en cualquier lugar de la clase pero poniéndole self.nombreAtributo

Los métodos se dividen en tres tipos:
 propios de la clase tienen un primer atributo que es self, haciendo 

*   Métodos de la clase: Puede ser llamado sin crear una instancia. Estos métodos tienen un primer atributo ***cls***. Puede llamar a otros métodos y atributos de la clase, pero no de la instancia. Se le debe anteponer  **@classmethod**
*   Métodos de instancia: Tiene que ser llamado desde una instancia. Estos métodos tienen un primer atributos ***self***
*   Métodos estáticos: Pude ser llamado sin crear una instancia. Se le debe anteponer **@staticmethod**

In [ ]:
import math

In [ ]:
class Circulo():
  ### Se define el constructor con las variables que se quieren asignar y se pueden declarar ahí mismo.
  ### Por ejemplo acá estamos pasando el radio del círculo
  def __init__(self,radio):
    self.radio=radio
  ### Por ejemplo si se quiere definir un método para el cálculo del área

  def area(self):
    return self.radio**2 * math.pi

In [ ]:
# Objeto de tipo Circulo con radio=5
circulo1=Circulo(5)
circulo1.area()

78.53981633974483

La herencia también se puede manejar de manera fácil. Podemos definir una clase FiguraGeométrica que tuviera el método área, para todos lo que heredan de ella. Y que la clase Circulo herede de ella.

In [ ]:
## Si queremos hacer la clase abstracta hay que ponerle el ABC
from abc import ABC, abstractmethod 
class FiguraGeometrica(ABC):

  ## Método abstracto, hace que las clases que hereden de ella lo tengan que implementar
  def area(self):
    pass

In [ ]:
class Circulo(FiguraGeometrica):
  def __init__(self,radio):
    self.radio=radio

  def area(self):
    return self.radio**2 * math.pi

In [ ]:
circulo1=Circulo(5)
circulo1.area()

78.53981633974483

Una clase puede tener atributos de la clase y atributos de las instancias. Los que son declarados con self son de instancia y los que se declaran encima de la clase son de la clase

In [ ]:
class Trabajador:
  bienvenida='Hola trabajador'

  ## Para que los atributos sean privados se deben poner con __ delante
  def __init__(self,nombre, edad, salario):
    self.__nombre=nombre
    self.__edad=edad
    self.__salario=salario

  def set_diasTrabajados(self,diasTrabajados):
    self.__diasTrabajados=diasTrabajados

  def set_salario(self,salario):
    self.__salario=salario
  
  def get_nombre(self):
    return self.__nombre

  def get_salario(self):
    return self.__salario

  def get_edad(self):
    return self.__edad

  def calSalario(self):
    return self.__diasTrabajados*self.__salario/24
  
  # Métodos de clase: Estos métodos deben llevar una variable cls y pueden acceder a los atributos de las clase pero no a los de la instancia
  @classmethod
  def saludo(cls):
    return cls.bienvenida
  
  # Métodos estáticos: son métodos que no dependen de los atributos de la clase ni la instancia, pueden ser usados sin instanciar un objeto
  @staticmethod
  def mensaje(m):
    print(m)

class Obrero(Trabajador):
  def calSalario(self):
    return 

In [ ]:
t=Trabajador('Juan Pérez', 35,3000000)
t.set_diasTrabajados(20)
print(t.calSalario())
print(t.saludo())
t.mensaje('Esto es una prueba de método estático')
Trabajador.mensaje('Esto es una prueba de que se peuden usar directamente')


2500000.0
Hola trabajador
Esto es una prueba de método estático
Esto es una prueba de que se peuden usar directamente


También se puede hacer una definición de los parámetros usando @property

Esta es otra forma de hacer los métodos get y set y que se pueda acceder y cambiar la variable según las opciones que se programen.

In [ ]:
class CirculoP():
  def __init__(self,radio):
    self.__radio=radio

  ### Haciendo una propiedad para radio
  @property
  def radio(self):
	  return self.__radio
  ## Declaración del set

  @radio.setter
  def radio(self, radio):
    if radio > 0 and isinstance(radio, float):
      self.__radio = radio
    else:
      print("Entre un radio válido")

  def area(self):
    return self.radio**2 * math.pi

In [ ]:
circulo=CirculoP(10)
circulo.radio=-5 # ya uno puede asignar un valor y llama el método de setter
circulo.radio
print(circulo)

Entre un radio válido
Circulo10


Existen otros método interesantes, por ejemplo:



*   **__eq__** es invocado cuando se hace una comparación de dos instancias de la clase a == b
*   **__add__** es invocado al sumar dos instancias de la clase a+b
*   **__str__** es invocado al imprimir el objeto, debe devolver una cadena




## Panda

Panda es una biblioteca que permite el trabajo con dos estructuras:

**DataFrame** que funciona como una tabla donde las columnas pueden ser etiquetadas, lo cuál puede hacer útil el almacenamiento de datos matriciales

**Series** que es una columna simple

In [ ]:
import pandas as pd

### Creación de DataFrame
Los DataFrame se pueden construir a partir de Diccionarios de Series o directamente.

In [ ]:
estudiantes=['Juan Pérez', 'Ana Hernández', 'Pedro García', 'Juana González']
notasEDA=[4.8,3.2,2,5]
notasIA=[4.3, 2.9,5,4.5]
df=pd.DataFrame({'Estudiantes':estudiantes, 'NotasEDA':notasEDA,'NotasIA': notasIA})
df

Estudiantes  NotasEDA  NotasIA
0      Juan Pérez       4.8      4.3
1   Ana Hernández       3.2      2.9
2    Pedro García       2.0      5.0
3  Juana González       5.0      4.5

In [ ]:
a=np.array(estudiantes)
a=np.append(a,notasEDA)
a=np.append(a, notasIA)
print(a)
a=np.matrix(np.reshape(a, (3,4)))
a=a.transpose()
print(a)
df = pd.DataFrame(a, columns=['Estudiante', 'NotasEDA', 'NotasIA'])
df


['Juan Pérez' 'Ana Hernández' 'Pedro García' 'Juana González' '4.8' '3.2'
 '2.0' '5.0' '4.3' '2.9' '5.0' '4.5']
[['Juan Pérez' '4.8' '4.3']
 ['Ana Hernández' '3.2' '2.9']
 ['Pedro García' '2.0' '5.0']
 ['Juana González' '5.0' '4.5']]


Estudiante NotasEDA NotasIA
0      Juan Pérez      4.8     4.3
1   Ana Hernández      3.2     2.9
2    Pedro García      2.0     5.0
3  Juana González      5.0     4.5

Se puede ir adicionando columnas al DataFrame

In [ ]:
df = pd.DataFrame({'Estudiantes':estudiantes})
print(df)
df['NotasEDA']=notasEDA
df['NotasIA']=notasIA
df

      Estudiantes
0      Juan Pérez
1   Ana Hernández
2    Pedro García
3  Juana González


Estudiantes  NotasEDA  NotasIA
0      Juan Pérez       4.8      4.3
1   Ana Hernández       3.2      2.9
2    Pedro García       2.0      5.0
3  Juana González       5.0      4.5

### Indexando
Para indexar un panda se puede usar:

.loc, .iloc, [] con etiquetas o con índices

In [ ]:
print(type(df['Estudiantes']))
print(df['Estudiantes'])

<class 'pandas.core.series.Series'>
0        Juan Pérez
1     Ana Hernández
2      Pedro García
3    Juana González
Name: Estudiantes, dtype: object


Selección por filas

In [ ]:
df.loc[2]

Estudiantes    Pedro García
NotasEDA                  2
NotasIA                   5
Name: 2, dtype: object

In [ ]:
df.loc[1:2]

Estudiantes  NotasEDA  NotasIA
1  Ana Hernández       3.2      2.9
2   Pedro García       2.0      5.0

Selección fila y columna:

Para seleccionar un conjunto de filas

In [ ]:
df.iloc[[0,2]]

Estudiantes  NotasEDA  NotasIA
0    Juan Pérez       5.0      4.3
2  Pedro García       3.0      3.0

Seleccionar un elemento determinado dando el número de fila y columna

In [ ]:
# df.iloc[indice_columna, indice_fila]
df.iloc[1,2]

2.9

Seleccionar rango de filas y rango de columnas

In [ ]:
# Acá funciona como el rango en arreglos
df.iloc[0:2,1:3]

NotasEDA  NotasIA
0       4.8      4.3
1       3.2      2.9

Seleccionando conjunto de filas y columnas específicas:

Por ejemplo seleccionando la fila 1 y 3 y columnas 0 y 2

In [ ]:
df.iloc[[1,3],[0,2]]

Estudiantes  NotasIA
1   Ana Hernández      2.9
3  Juana González      4.5

Se puede hacer cambios con iloc a unas posiciones específicas:
Por ejemplo:Cambiar la nota de la fila 0 y 1 de IA

In [ ]:
print(df)
df.iloc[0:2,1]=[5,5]
df

      Estudiantes  NotasEDA  NotasIA
0      Juan Pérez       5.0      4.3
1   Ana Hernández       5.0      2.9
2    Pedro García       2.0      5.0
3  Juana González       5.0      4.5


Estudiantes  NotasEDA  NotasIA
0      Juan Pérez       5.0      4.3
1   Ana Hernández       5.0      2.9
2    Pedro García       2.0      5.0
3  Juana González       5.0      4.5

Seleccionando por una condición

In [ ]:
df.loc[df['NotasIA'] >= 4]

Estudiantes  NotasEDA  NotasIA
0      Juan Pérez       5.0      4.3
2    Pedro García       2.0      5.0
3  Juana González       5.0      4.5

Seleccionando por más de una condición

In [ ]:
df.loc[(df['NotasIA'] >= 4) & (df['NotasEDA']>=4)]

Estudiantes  NotasEDA  NotasIA
0      Juan Pérez       5.0      4.3
3  Juana González       5.0      4.5

Se pueden hacer actualizaciones por condición.
Suponga que queremos cambiar la nota de EDA e IA para aquellos cuya nota de EDA sea 2, vamos a ponerle 3 en ambas

In [ ]:
df.loc[(df['NotasEDA'] ==2), ['NotasEDA', 'NotasIA']] = [3,3]
df

Estudiantes  NotasEDA  NotasIA
0      Juan Pérez       5.0      4.3
1   Ana Hernández       5.0      2.9
2    Pedro García       3.0      3.0
3  Juana González       5.0      4.5

### Cargar datos desde un CSV

Se puede cargar un conjunto de datos desde un csv:

Por ejemplo

In [ ]:
iris=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', sep=',', header=None,names=[])

In [ ]:
iris.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [ ]:
california_housing_dataframe = pd.read_csv("https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv", sep=",")
california_housing_dataframe.describe() # Estadísticos descriptivos de los datos

longitude      latitude  ...  median_income  median_house_value
count  17000.000000  17000.000000  ...   17000.000000        17000.000000
mean    -119.562108     35.625225  ...       3.883578       207300.912353
std        2.005166      2.137340  ...       1.908157       115983.764387
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.790000     33.930000  ...       2.566375       119400.000000
50%     -118.490000     34.250000  ...       3.544600       180400.000000
75%     -118.000000     37.720000  ...       4.767000       265000.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

In [ ]:
california_housing_dataframe.head(7) # las primeras 7 filas del DataFrame

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0
5    -114.58     33.63  ...         3.3438             74000.0
6    -114.58     33.61  ...         2.6768             82400.0

[7 rows x 9 columns]